// Small, framework-free helpers around window.__ATLAS_CONFIG and the
// per-browser link-mode preference. Everything here is safe to import from
// SSR contexts — every window access is guarded.
//
// The runtime config bootstrap ships in static/atlas-config.js, which is
// generated by docusaurus.config.js at build time. It sets
//   window.__ATLAS_CONFIG = {
//     repoRoot, githubRepo, githubRef, jetbrainsProject, defaultMode,
//     localMissing,
//   }
// before hydration.

export type LinkMode = 'jetbrains' | 'github';

export interface AtlasRuntimeConfig {
  repoRoot: string;
  githubRepo: string;
  githubRef: string;
  jetbrainsProject: string;
  defaultMode: LinkMode;
  localMissing: boolean;
}

const STORAGE_KEY = 'atlasLinkMode';
export const LINK_MODE_EVENT = 'atlas-link-mode-changed';

const DEFAULT_CONFIG: AtlasRuntimeConfig = {
  repoRoot: '',
  githubRepo: 'apache/ozone',
  githubRef: 'master',
  jetbrainsProject: 'ozone',
  defaultMode: 'github',
  localMissing: true,
};

/** Read the injected runtime config, falling back safely during SSR. */
export function readConfig(): AtlasRuntimeConfig {
  if (typeof window === 'undefined') return DEFAULT_CONFIG;
  const c = (window as unknown as {__ATLAS_CONFIG?: Partial<AtlasRuntimeConfig>}).__ATLAS_CONFIG;
  if (!c) return DEFAULT_CONFIG;
  return {...DEFAULT_CONFIG, ...c};
}

/** Read the effective mode: localStorage override, else config default. */
export function readMode(cfg: AtlasRuntimeConfig = readConfig()): LinkMode {
  if (typeof window === 'undefined') return cfg.defaultMode;
  const stored = window.localStorage.getItem(STORAGE_KEY);
  if (stored === 'jetbrains' || stored === 'github') return stored;
  return cfg.defaultMode;
}

/** Persist a mode choice and notify subscribers in the same tab. */
export function writeMode(mode: LinkMode): void {
  if (typeof window === 'undefined') return;
  window.localStorage.setItem(STORAGE_KEY, mode);
  // storage events don't fire in the tab that made the change, so we
  // dispatch a custom event too. Both are handled by subscribeMode.
  window.dispatchEvent(new CustomEvent(LINK_MODE_EVENT, {detail: mode}));
}

/** Subscribe to same-tab and cross-tab mode changes. Returns an unsubscribe. */
export function subscribeMode(cb: (mode: LinkMode) => void): () => void {
  if (typeof window === 'undefined') return () => {};
  const onCustom = (e: Event) => {
    const detail = (e as CustomEvent<LinkMode>).detail;
    if (detail === 'jetbrains' || detail === 'github') cb(detail);
  };
  const onStorage = (e: StorageEvent) => {
    if (e.key !== STORAGE_KEY) return;
    if (e.newValue === 'jetbrains' || e.newValue === 'github') cb(e.newValue);
  };
  window.addEventListener(LINK_MODE_EVENT, onCustom);
  window.addEventListener('storage', onStorage);
  return () => {
    window.removeEventListener(LINK_MODE_EVENT, onCustom);
    window.removeEventListener('storage', onStorage);
  };
}

/**
 * Build the href for a source-file link.
 * - jetbrains → jetbrains://idea/navigate/reference?project=<p>&path=<full>&line=<n>
 * - github    → https://github.com/<repo>/blob/<ref>/<path>#L<n>
 * The JetBrains scheme wants an absolute path in the local checkout, so we
 * prepend repoRoot when it is set. If repoRoot is empty the URL still opens
 * IDEA and IDEA falls back to searching by relative path; that is the
 * documented behavior of the navigate handler.
 */
export function buildHref(
  cfg: AtlasRuntimeConfig,
  mode: LinkMode,
  relPath: string,
  line?: number,
): string {
  const trimmed = relPath.replace(/^\/+/, '');
  if (mode === 'jetbrains') {
    const project = encodeURIComponent(cfg.jetbrainsProject || 'ozone');
    const abs = cfg.repoRoot ? `${cfg.repoRoot.replace(/\/+$/, '')}/${trimmed}` : trimmed;
    const pathParam = encodeURIComponent(abs);
    const lineParam = line != null ? `&line=${line}` : '';
    return `jetbrains://idea/navigate/reference?project=${project}&path=${pathParam}${lineParam}`;
  }
  const repo = cfg.githubRepo || 'apache/ozone';
  const ref = cfg.githubRef || 'master';
  const anchor = line != null ? `#L${line}` : '';
  return `https://github.com/${repo}/blob/${ref}/${trimmed}${anchor}`;
}
