import React, {useMemo, useState} from 'react';
import Link from '@docusaurus/Link';
import atlasMin from '@site/docs/_data/atlas.min.json';

interface MinRow {
  fqcn: string;
  slug: string;
  shortName: string;
  role: string;
  component: string;
  feature: string;
  kind: string;
  logic_weight: string;
  difficulty: number;
  study_minutes: number;
  read_order_hint: number;
  tags: string[];
}
const ROWS: MinRow[] = atlasMin as MinRow[];

const ALL_TAGS = Array.from(new Set(ROWS.flatMap((r) => r.tags))).sort();
const ALL_COMPONENTS = Array.from(new Set(ROWS.map((r) => r.component))).sort();
const ALL_FEATURES = Array.from(new Set(ROWS.map((r) => r.feature))).sort();
const ALL_LOGIC = ['data-only', 'mixed', 'logic-heavy'];

type SortKey = 'read_order_hint' | 'study_minutes' | 'difficulty' | 'component';

interface Query {
  tags: string[];
  component: string;
  feature: string;
  logic_weight: string;
  fqcnContains: string;
  sort: SortKey;
}

const EMPTY: Query = {
  tags: [],
  component: '',
  feature: '',
  logic_weight: '',
  fqcnContains: '',
  sort: 'read_order_hint',
};

function apply(q: Query): MinRow[] {
  const needle = q.fqcnContains.toLowerCase();
  const rows = ROWS.filter((r) => {
    if (q.component && r.component !== q.component) return false;
    if (q.feature && r.feature !== q.feature) return false;
    if (q.logic_weight && r.logic_weight !== q.logic_weight) return false;
    if (needle && !r.fqcn.toLowerCase().includes(needle)) return false;
    if (q.tags.length > 0 && !q.tags.every((t) => r.tags.includes(t))) return false;
    return true;
  });
  rows.sort((a, b) => {
    switch (q.sort) {
      case 'read_order_hint':
        return (a.read_order_hint ?? 0) - (b.read_order_hint ?? 0);
      case 'study_minutes':
        return (a.study_minutes ?? 0) - (b.study_minutes ?? 0);
      case 'difficulty':
        return (a.difficulty ?? 0) - (b.difficulty ?? 0);
      case 'component':
        return a.component.localeCompare(b.component) || a.feature.localeCompare(b.feature);
    }
  });
  return rows;
}

function toModule(id: string, q: Query): string {
  const selectors: string[] = [];
  if (q.component) selectors.push(`{kind: 'match', component: '${q.component}'}`);
  if (q.feature) selectors.push(`{kind: 'match', feature: '${q.feature}'}`);
  if (q.logic_weight) selectors.push(`{kind: 'match', logic_weight: '${q.logic_weight}'}`);
  for (const t of q.tags) selectors.push(`{kind: 'tag', tag: '${t}'}`);
  return [
    `// Auto-generated by /view/builder. Drop under scripts/views/${id}.js`,
    'module.exports = {',
    `  id: '${id}',`,
    `  title: '${id.replace(/-/g, ' ')}',`,
    `  description: '',`,
    `  tags: ${JSON.stringify(q.tags)},`,
    `  selectors: [`,
    ...selectors.map((s) => `    ${s},`),
    `  ],`,
    '};',
    '',
  ].join('\n');
}

export default function ViewBuilder(): JSX.Element {
  const [q, setQ] = useState<Query>(EMPTY);
  const rows = useMemo(() => apply(q), [q]);

  const totalMin = rows.reduce((s, r) => s + (r.study_minutes ?? 0), 0);
  const toggleTag = (t: string) =>
    setQ((prev) => ({...prev, tags: prev.tags.includes(t) ? prev.tags.filter((x) => x !== t) : [...prev.tags, t]}));

  const onSave = () => {
    const name = prompt('Save this query under a name (letters, digits, dash):') ?? '';
    const id = name.replace(/[^a-z0-9-]/gi, '-').toLowerCase();
    if (!id) return;
    const key = `atlasSavedView:${id}`;
    localStorage.setItem(key, JSON.stringify(q));
    alert(`Saved to localStorage as "${id}".`);
  };

  const onExport = () => {
    const name = prompt('Export id (letters, digits, dash):') ?? '';
    const id = name.replace(/[^a-z0-9-]/gi, '-').toLowerCase();
    if (!id) return;
    const body = toModule(id, q);
    const blob = new Blob([body], {type: 'application/javascript'});
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${id}.js`;
    a.click();
    setTimeout(() => URL.revokeObjectURL(url), 200);
  };

  return (
    <div className="atlas-viewbuilder">
      <div className="atlas-viewbuilder__pane atlas-viewbuilder__pane--left">
        <h3>Filter</h3>
        <div className="atlas-viewbuilder__row">
          <label>Component</label>
          <select value={q.component} onChange={(e) => setQ({...q, component: e.target.value})}>
            <option value="">(any)</option>
            {ALL_COMPONENTS.map((c) => <option key={c} value={c}>{c}</option>)}
          </select>
        </div>
        <div className="atlas-viewbuilder__row">
          <label>Feature</label>
          <select value={q.feature} onChange={(e) => setQ({...q, feature: e.target.value})}>
            <option value="">(any)</option>
            {ALL_FEATURES.map((f) => <option key={f} value={f}>{f}</option>)}
          </select>
        </div>
        <div className="atlas-viewbuilder__row">
          <label>logic_weight</label>
          <select value={q.logic_weight} onChange={(e) => setQ({...q, logic_weight: e.target.value})}>
            <option value="">(any)</option>
            {ALL_LOGIC.map((l) => <option key={l} value={l}>{l}</option>)}
          </select>
        </div>
        <div className="atlas-viewbuilder__row">
          <label>fqcn contains</label>
          <input value={q.fqcnContains} onChange={(e) => setQ({...q, fqcnContains: e.target.value})} placeholder="e.g. Snapshot" />
        </div>
        <div className="atlas-viewbuilder__row">
          <label>Sort</label>
          <select value={q.sort} onChange={(e) => setQ({...q, sort: e.target.value as SortKey})}>
            <option value="read_order_hint">read_order_hint</option>
            <option value="study_minutes">study_minutes</option>
            <option value="difficulty">difficulty</option>
            <option value="component">component,feature</option>
          </select>
        </div>
        <div className="atlas-viewbuilder__tags">
          <label>Tags (AND)</label>
          <div>
            {ALL_TAGS.map((t) => (
              <button
                key={t}
                onClick={() => toggleTag(t)}
                className={`atlas-viewbuilder__tag ${q.tags.includes(t) ? 'is-active' : ''}`}
                type="button"
              >{t}</button>
            ))}
          </div>
        </div>
        <div className="atlas-viewbuilder__actions">
          <button type="button" className="button button--secondary button--sm" onClick={onSave}>Save locally</button>
          <button type="button" className="button button--primary button--sm" onClick={onExport}>Export as view module</button>
        </div>
      </div>
      <div className="atlas-viewbuilder__pane atlas-viewbuilder__pane--right">
        <h3>{rows.length} classes · {totalMin} min</h3>
        <ol>
          {rows.slice(0, 500).map((r) => (
            <li key={r.fqcn}>
              <Link to={`/class/${r.slug}`}>{r.shortName}</Link>{' '}
              <small><code>{r.component}/{r.feature}</code> · {r.study_minutes ?? 0}m · d{r.difficulty ?? '?'} · {r.logic_weight}</small>
              <br />
              <em>{r.role}</em>
            </li>
          ))}
        </ol>
        {rows.length > 500 && <p><em>Showing first 500 of {rows.length}.</em></p>}
      </div>
    </div>
  );
}
